---
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: Build
jobs:
  build:
    name: Build contracts
    runs-on: runs-on=${{ github.run_id }}/family=c5a.8xlarge+c6a.8xlarge/image=ubuntu24-full-x64/extras=s3-cache
    steps:
      - name: Setup RunsOn
        uses: runs-on/action@v2
        with:
          metrics: cpu,network,memory,disk,io
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libudev-dev build-essential pkg-config libssl-dev
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install plugins
        run: cargo +stable install cargo-make cargo-near
      - name: Compile contract
        run: cargo make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contracts
          path: res/aurora-controller*.wasm

  publish:
    name: Publish contracts
    runs-on: runs-on=${{ github.run_id }}/family=c5a.xlarge+c6a.xlarge/image=ubuntu24-full-x64
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Publish contracts for ${{ github.ref }} release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: contracts/aurora-controller*.wasm
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
