name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  checks:
    name: Run ${{ matrix.action }}
    runs-on: runs-on=${{ github.run_id }}/family=c5a.8xlarge+c6a.8xlarge/image=ubuntu24-full-x64
    strategy:
      fail-fast: false
      matrix:
        action: [ fmt, clippy, tests ]
    steps:
      - name: Install Dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libudev-dev
          version: 1.0
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install plugins
        run: cargo install cargo-make cargo-near
      - name: Running ${{ matrix.action }}
        run: cargo make ${{ matrix.action }}
