name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  checks:
    name: Run ${{ matrix.action }}
    runs-on: k8s-infrastructure-generic
    strategy:
      fail-fast: false
      matrix:
        action: [ fmt, clippy, tests ]
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libudev-dev build-essential pkg-config libssl-dev
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install plugins
        run: cargo install cargo-make cargo-near
      - name: Running ${{ matrix.action }}
        run: cargo make ${{ matrix.action }}
