name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  checks:
    name: Run ${{ matrix.action }}
    runs-on: github-hosted-heavy-runner
    strategy:
      fail-fast: false
      matrix:
        action: [ fmt, clippy, tests ]
    steps:
      - name: Install Dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libudev-dev
          version: 1.0
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install plugins
        run: cargo install cargo-make cargo-near
      - name: Running ${{ matrix.action }}
        run: cargo make ${{ matrix.action }}
