name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  checks:
    name: Run ${{ matrix.action }}
    runs-on: runs-on=${{ github.run_id }}/runner=rust-near-integration-special-16cpu-32gb
    strategy:
      fail-fast: false
      matrix:
        action: [ fmt, clippy, tests ]
    steps:
      - name: Setup RunsOn
        uses: runs-on/action@v2
        with:
          metrics: cpu,network,memory,disk,io
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libudev-dev build-essential pkg-config libssl-dev
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install plugins
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: install
          args: cargo-make cargo-near
      - name: Running ${{ matrix.action }}
        run: cargo make ${{ matrix.action }}
